query allData($first: Int, $orderBy: ProjectOrderByInput) {
  global(where: { uid: "an_portfolio" }) {
    brand
  }
  page(where: { uid: "about" }) {
    title
    info1
  }
  projects(first: $first, orderBy: $orderBy) {
    uid
    agency
    brand
    title
    type
    info {
      html
    }
    thumb {
      url(transformation: { document: { output: { format: jpg } } })
      fileName
    }
    view {
      ... on Video {
        width
        height
        type
        video {
          url
        }
        poster {
          url(transformation: { document: { output: { format: jpg } } })
        }
      }
      ... on Iframe {
        height
        type
        url
        width
      }
      ... on Gallery {
        width
        type
        height
        gallery {
          url(transformation: { document: { output: { format: jpg } } })
        }
      }
    }
  }
}
