#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

function changed {
  git diff --name-only HEAD@{1} HEAD | grep "^$1" > /dev/null 2>&1
}

if changed 'package-lock.json'; then
  echo;
  echo "📦 IMPORTANT! package-lock.json changed.";
  echo "Running npm install to bring your dependencies up to date.";
  npm install
  echo;
fi
